services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_ENVIRONMENT=PRODUCTION
      - DEBUG=False
    restart: unless-stopped

volumes:
  static_volume: