services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_ENVIRONMENT=DEVELOPMENT
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

volumes:
  static_volume: